"""Shared dataclasses and structural types."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd


@dataclass
class MarketBundle:
    """Loaded raw market data bundle."""

    daily: pd.DataFrame
    minute5: pd.DataFrame
    start_date: pd.Timestamp
    end_date: pd.Timestamp
    codes: List[str]
    source_notes: Dict[str, str]


@dataclass
class FeatureBundle:
    """Feature tables by frequency."""

    by_freq: Dict[str, pd.DataFrame]
    price_table_daily: pd.DataFrame
    meta: Dict[str, object]


@dataclass
class TrainArtifacts:
    """Trained model objects and related metadata."""

    stock_model: object
    timing_model: object
    portfolio_model: object
    execution_model: object
    fill_values: Optional[pd.Series]
    train_meta: Dict[str, object]


@dataclass
class OutputArtifacts:
    """Output paths generated by a run."""

    output_dir: Path
    files: Dict[str, Path]

